apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop-prod
  namespace: default
  labels:
    contrast: nodejs-protect
spec:
  selector:
    matchLabels:
      app: juice-shop-prod
  template:
    metadata:
      labels:
        app: juice-shop-prod
    spec:
      containers:
        - image: bkimminich/juice-shop
          name: juice-shop
          ports: 
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service-prod
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: juice-shop-prod
