apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: default
  labels:
    contrast: nodejs-assess
spec:
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
        - image: bkimminich/juice-shop
          name: webgoat
          ports: 
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: juice-shop
