apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflicks
  namespace: default
  labels:
    contrast: dotnet-core-assess
spec:
  selector:
    matchLabels:
      app: netflicks
  template:
    metadata:
      labels:
        app: netflicks
    spec:
      containers:

        - image: pprofili/netflicks:contrast
          name: netflicks
          ports: 
          - containerPort: 80
          env: 
          - name: ConnectionStrings__DotNetFlicksConnection
            value: Server=tcp:127.0.0.1,1433;Initial Catalog=DotNetFlicksDb;Persist Security Info=False;User ID=sa;Password=reallyStrongPwd123;MultipleActiveResultSets=False;
        
        - name: mssqldb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
          - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "reallyStrongPwd123"
---
apiVersion: v1
kind: Service
metadata:
  name: netflicks-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netflicks
