apiVersion: apps/v1
kind: Deployment
metadata:
  name: terracotta-bank
  namespace: default
  labels:
    contrast: java-assess
spec:
  selector:
    matchLabels:
      app: terracotta-bank
  template:
    metadata:
      labels:
        app: terracotta-bank
    spec:
      containers:
        - image: contrastsecuritydemo/terracotta-bank:3.0-no-agent
          name: terracotta-bank
          ports: 
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: terracotta-bank-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: terracotta-bank
