apiVersion: apps/v1
kind: Deployment
metadata:
  name: webgoat
  namespace: default
  labels:
    contrast: java-assess
spec:
  selector:
    matchLabels:
      app: webgoat
  template:
    metadata:
      labels:
        app: webgoat
    spec:
      containers:
        - image: webgoat/webgoat-7.1
          name: webgoat
          ports: 
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webgoat-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: webgoat
